反転、実装しました〜
calvokobe/lesson01 pull request #6
Opened 2020-06-15 09:24 UTC by calvokobe

レビューお願いいたします〜

2020-06-15 10:38 UTC, hnakai-bs approved these changes

2020-06-15 10:38 UTC, hayato-kobe-pro commented on 3-4/main.js
> +
引数をstr1, str2に入れてコードを短くすると尚良いと思います！

2020-06-15 10:38 UTC, hayato-kobe-pro commented on 3-4/main.js
> +onst arg1 = String(process.argv[2])
cが抜けてます！

2020-06-16 03:02 UTC, calvokobe commented on 3-4/main.js
> +onst arg1 = String(process.argv[2])
うわっ、ダサっ！苦笑
以後、気をつけるようにします！

2020-06-16 03:03 UTC, calvokobe commented on 3-4/main.js
> +
なるほど、そういうところ、まだまだ抜けてます、これからも指摘・アドバイス、よろしくお願いいたします！

2020-06-16 03:21 UTC, yuki-katayama commented
LGTM!

2020-06-16 03:22 UTC, yuki-katayama approved these changes
LGTM!

2020-06-16 11:27 UTC, ryohorie approved these changes

2020-06-16 11:29 UTC, ryohorie requested changes
NGです。
コマンドライン引数が 4桁, 5桁になっても動作するように実装してください

2020-06-24 10:34 UTC, yuki-katayama approved these changes
修正後バッチリです！

2020-06-24 10:34 UTC, yuki-katayama approved these changes

2020-07-04 14:04 UTC, ryohorie approved these changes
👍

2020-07-27 05:05 UTC, merged